GabrielDosReis/ipr

CMakeLists.txt
src/interface.cxx
src/io.cxx

I took the liberty and enrolled the CMake build scripts into my "pimp your CMake" customer care program. They were updated to the brave "new" post-3.0 era. I set the minimum to 3.5 (might work under it, let me know if it's an issue, two Ubuntu LTS releases back is "old enough" for a practical stand point).
Some notes about the update:
- I tried to stick to a sleek, modern indentation style for readability
- The script is 100% declarative, as per modern guidelines
- Generator expresions are used when compiler or platform specific behavior is requested
- I turned the warning level as high up as possible and selectively turned off noisy warnings. Let me know if selective turn offs cause new warning in older versions (where the switch does not exist yet) and I'll put them behind version check …

Update CMake scripts to post-3.0

---

.gitignore
src/impl.cxx

Collapse:
```c++
Lexicon::make_class(const ipr::Region& pr) {
impl::Class* c = types.make_class(pr, anytype);
c->constraint = &classtype;
return c;
}
```
to
```c++
Lexicon::make_class(const ipr::Region& pr) {
return types.make_class(pr, classtype);
}
```
Also, make_union, was, mistakenly?, not updating its type to `enumtype`. This checkin fixes it as well.
Misc: trailing whitespaces cleaned.

Simplify Lexicon::make_{enum,class,namespace,union} methods.

---

CMakeLists.txt
cmake/UseLATEX.cmake
doc/CMakeLists.txt

I wanted to read up on the usage of IPR and saw that the docs are in TeX, so naturally I went ahead and added them to the CMake build. I guess most users are not interested in building the docs themselves (to add a LaTeX compiler to the default dependencies), so the default is that `BUILD_DOC` is `OFF`.
Tested on Windows with MikTeX and Ninja, worked like a charm.

Build docs with CMake

---

src/io.cxx

Fix missing Rvalue_Reference in io causing crash.

---

include/ipr/impl

Pointers to ipr nodes need to be const as everything at the interface level is const&. This bug is likely a simple typo.
These appear to be the only instances of this problem that I can find.

Named_map pointer in impl should be const

---

include/ipr/impl

I fail to build the IPR library with the latest MSVC compiler due to build trying to select the templated overload for ipr::String. This results in a "cannot instantiate abstract class" because the parameter is passed by value.
This PR resolves that issue but please chime in on whether it is the right fix or whether it should be needed at all.
```
1>E:\src\ipr\src\impl.cxx(875,13): error C2259: 'ipr::String': cannot instantiate abstract class
1>E:\src\ipr\include\ipr/interface(608): message : see declaration of 'ipr::String'
1>E:\src\ipr\src\impl.cxx(875,13): message : due to following members:
1>E:\src\ipr\src\impl.cxx(875,13): message : 'void ipr::Node::accept(ipr::Visitor &) const': is abstract
1>E:\src\ipr\include\ipr/interface(598): message : see declaration of 'ipr::Node::accept' …
```

Fixed build error from ipr::String selecting scalar compare overload.

---

include/ipr/interface

Replace std::iterator which was deprecated in C++17 with standard iterator implementation.

Replaced deprecated std::iterator base

---

.github/workflows/docs.yaml
.github/workflows/main.yml

Installing latex on ubuntu takes a bit more time, it is not included in the default job.
After this patch, when there are changes to the doc folder, a separate CI job will build the latex files as well.

Improvements to CI

---

.github/workflows/mac.yml

I do not know what are the requirements of this project in terms of platform support. 
This patch adds a mac builder to the CI, and it picks up Clang as a compiler.
Feel free to just close it if macs are not supported.

Add mac builder.

---

.github/workflows/docs.yaml

The other builder will always trigger if there is a non-doc change, so this can help to avoid redundant work.

Doc builder only builds doc target

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/traversal.cxx

Fix #61 
Fix #59 
Add a name for deduction guides, even if standard C++ pretends they don't have names

Update the ipr Name sub-hierarchy

---

include/ipr/impl
include/ipr/interface
include/ipr/traversal
src/impl.cxx
src/io.cxx
src/traversal.cxx

With the push to have expressions with their own source locations, there is less benefit to having names be part of the general `Expr` hierarchy.
This is a breaking change from [Classic IPR](https://github.com/GabrielDosReis/ipr/commit/3fc82cb0a38932b82f06a2efda4087ddad61fa84).

Move Name out of Expr hierarchy

---

include/ipr/impl
include/ipr/io
src/io.cxx

Really fix #68 this time, and the resulting build break.  Also fixed a few valueless warnings enabled by default by recent versions of MSVC.

Fix build break

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

and adjust uses and definitions.
This is a breaking change, but the renaming will create less FAQ/confusion over the long term.

Rename type `Template` to `Forall`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

A type declaration can appear at non-type scope, e.g. it can be a local class.
Fixes #70

Owner of home scope of a type declaration

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

This is a breaking change from previous versions.  When you sync to this version, you need to make the following changes in your codebase:
1. Change `Template` to `Forall`
2.  change `Named_map` to `Template`
in that order, or chaos ensues.

Rename Named_map to Template

---

CMakeLists.txt

Similarly to the variable used for the `ipr/include` path this variable should be relative to the project. This will allow ipr to built as part of another larger CMake project where ipr is not the CMake root.

Made CMake variable relative

---

include/ipr/impl
include/ipr/interface

At some point in the design of the IPR, we decided that just about any expression should be subject to parameterization -- not just declarations, but also types (which later gave rise to template aliases, that CWG unwisely renamed to alias templates) and classic expressions.  A corollary of that is that every declaration was potentially the result of an instantiation.
This patch starts a series where we take a slightly different approach to implementing that idea by representing request for specialization as distinct expression nodes.  First we remove the remnant of the previous implementation tactic.

Simplify ipr::Decl a bit

---

include/ipr/impl
include/ipr/interface
include/ipr/io
src/impl.cxx
src/interface.cxx

The field `Node::node_id` was introduced as a way to aid with persistent storage identification of IPR nodes.  However, with the move towards multiple on-disk projections of IPR nodes and the out-of-date XPR projection, that member is no longer as useful as it used to be.  Furthermore it is not really needed for reproducible IPR node construction.

Remove Node::node_id

---

include/ipr/interface
src/impl.cxx

Add a convenience for constructing an empty `String` node.  It is useful for creating declarations that would normally have an `Identifier` name, but may be left missing such as in an unnamed parameter declaration.

Add accessor for empty String

---

include/ipr/impl
src/impl.cxx

All classes deriving from `unique_decl` have the same functional overrider for `decl_set()` -- by the very semantics of `unique_decl`.  This patch consolidates those overriders at one place.  It also fixes a thinko from last commit.

Commonalize unique_decl::decl_set overrider

---

include/ipr/impl

Simplify the implementation of various homogeneous sequences of `unique_decl`: `homogeneous_sequence`, `homogeneous_scope`, `homogeneous_region`.  The bulk of the simplification is removal of code --  good simplification!
It is apparent that most of the code was written before C++11 :-)

Simplify sequences of unique_decl

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

Use `Optional` in the implementation file more often to indicate items that are optional.
Note: this is not the same as replacing all pointer types `T*` with `Optional<T>`.

Use Optional more often

---

include/ipr/impl
src/impl.cxx

Currently, we have 3 factory functions for new, but they do not cover one use case: having placement arguments but not having initializers. We have 2 options, either add a 4th factory, or consolidate factory functions to have one of them. I went with latter as I believe it makes creating New nodes easier (we do not need to have 4 code paths). Let me know if other solution is preferred.

Consolidate factory functions for New

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/traversal.cxx
tests/unit-tests/CMakeLists.txt
tests/unit-tests/conversions.cpp

Address some of the implicit C++ conversions #36.
This includes tests that help demonstrate how the IPR represents C++ source code and how to construct the nodes. This feels like a very effective way of providing documentation through practical examples.

Added conversion nodes and demonstrative tests.

---

src/io.cxx

We recently added a Suffix name. This patch adds printing for it.
```operator ""_km```
will be printed as
```operator "_km"```
in XPR.

io.cxx: Add printing for Suffix

---

include/ipr/impl
include/ipr/io
src/impl.cxx
src/io.cxx
tests/unit-tests/simple.cpp

Add support for creation and printing of source locations.
Filemap is changed from stable_farm to a vector to support lookup by index.
There is no unification of file name is performed as it is assumed that the user will maintain a map of source file names to ipr::File_index as locations are translated into the IPR.

Add support for source locations

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx
tests/unit-tests/conversions.cpp

The IPR library did not originally have a class to directly represent optionality.  That meant that in order to ensure non-forgetful and safe consumption of optional data, some notions were unfortunately duplicated in the class hierarchy.  That is the case for `ipr::If_then` and `ipr::If_then_else`.  This patch merge those classes into a single `ipr::If`, taking advantage of the availability of `ipr::Optional`.  I took the opportunity to rename accessor names - to ensure consumption sites are appropriately updated.
This is a source breaking change.

Merge ipr::If_then and ipr::If_then_else

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

This patch merges the existing node classes `ipr::Paren_expr` and `ipr::Initializer_list` in the single notion of `ipr::Enclosure`.  It partially addresses the issues reported in #19

Merge ipr::Paren_expr and ipr::Initializer_list

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

With the C++17 reclassification of value categories to [guarantee copy elision in certain circumstances](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0135r0.html) the meaning of `T(x, y)` (modeled by `ipr::Datum`) changed, that expression no longer really constructs a data or an rvalue.  Rather it is only a description of an object construction (note: the object itself isn't constructed).  A separate operation -- temporary materialization -- is to perform that action of actually constructing the object.  This patch incorporate that semantic refinement in the IPR.  
The class `ipr::Datum` is renamed to `ipr::Construction` to encapsulate the notion of object construction description.  It is now a unary structure since the `type()` is also the type of the object being …

Rename ipr::Datum to ipr::Construction

---

include/ipr/impl

The implementation of `singleton_declset::get` has an off-by-one error in its implementation.  Fixed.

Fix off by one index error

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

15+ years ago, we were hoping that WG21 would fix the mistake of making the return type of `size()` an unsigned type.  We defaulted to `int` as just the natural integer type of C and C++.  Despite all efforts over the years to convince WG21 (the most recent being with `std::span`), it is with sad heart that we have to make the change here to minimize the friction with using the standard library

Change return type of size()

---

include/ipr/impl
include/ipr/interface
include/ipr/io
src/impl.cxx
src/io.cxx

This PR simplifies a bit the interface of `Parameter_list`, and the construction ceremony of such node.  In the process, it adds a bit of typeful distinction between a mapping level and a parameter position - catching an instance where one is confused for the other.
Partially fix #35

Simplify Parameter_list

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

Introduce `ipr::Symbol` for symbolic values such as `nullptr`.

Symbolic values

---

include/ipr/impl
src/impl.cxx

This patch introduces a slight source breaking change for the consumers that call the factory functions for `do`, `while`, and `switch` statements with the children nodes.
Fix #96

Allow empty shell controlled statements

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

Symbol values are core values, so they should be unified.  This patch adds that capability, in addition to explicitly providing the facility of symbol overloading.

Unify ipr::Symbol

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

Revert from Classic IPR design decision to treat `this` no different from any other function parameter.
Fix #28

Explicit representation of "this"

---

include/ipr/impl
include/ipr/interface
include/ipr/utility
src/impl.cxx

Introduce `util::ref` to automate implementation of logical references as pointers.

Miscellaneous cleanup [1/n]

---

include/ipr/impl
src/impl.cxx

More cleanups.  Define more `final` functions `as inline`.
Source breaking change: `Block::add_stmt()` and `Block::add_handler()` now take references to node of interface class types, instead of pointers.

Miscellaneous cleanup [3/n]

---

CMakeLists.txt
include/ipr/impl
include/ipr/interface
src/impl.cxx
tests/unit-tests/CMakeLists.txt

This patch adds a `Region::global()` predicate that holds for the global region, i.e. the region of the global scope.
Fix #33 .
Note: the patch also ensures that the tests are run with flags consistent with the build.  Someone more versed in CMake should have a look and devise a better way to do this so we don't have two places to update.

Predicate for testing global region

---

include/ipr/impl
src/impl.cxx

The checking to implement representation for lambda (#142) left out  these important pieces of code.  Fixed thusly.

Forgotten Lambda code

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

There was too much energy spent in trying to capture where an entity really belong or who owns it.  The `membership()` interface function is really redundant.  Removed.
Fix #170.

Remove membership() as redundant

---

src/impl.cxx
tests/unit-tests/simple.cpp

Previously, we picked the most general unary_compare overload that
compared the addess of Linkage to Linkage::rep. As a result, those never
compared equal and we ended up creating a new node for linkage each time
Lexicon::cxx_linkage was called. This patch adds an overload to resolve
this problem.

Fix duplicate linkage nodes

---

tests/unit-tests/CMakeLists.txt
tests/unit-tests/conversions.cpp
tests/unit-tests/main.cpp
tests/unit-tests/simple.cpp

Moving doctest's main function into a separate main.cpp makes it clearer
that it is distinguished from regular tests. All tests now follow the
same pattern (include doctest).
I also changed the includes to use <> instead of "", because doctest is
on the search path of the test files, not relative to them.

chore: move doctest's main function into main.cpp

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
tests/unit-tests/CMakeLists.txt
tests/unit-tests/words.cxx

Back in the 2000s, we didn't have `constexpr` to enforce static initialization of global objects of class types with constructors, so we 'manually' constructed many commonly used objects at startup; these include allocating some statically known `String` objects.  This patch makes such `String` objects statically allocated.  In the process, it also removed uses of `const char*` and `std::string` as interface for trucking character strings.  A follow up patch will switch to consistent uses of UTF-8 encoded character strings for the internal representation.

Miscellaneous cleanup 5/n

---

include/ipr/impl
include/ipr/utility
src/impl.cxx

Continuing the cleanup series.
Explicitly express the IPR nodes are non-copyable and non-moveable.  Document the expected order of the argument supplied to the ordering objects when inserting into `util::rb_tree` objects.

Miscellaneous cleanup 6/n

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
src/io.cxx

The `Seuquence` interface is exposed as a sequence iterated over by a bidirectional iterator even if in some circumstances it admits a random access operation (via the protected operation `get()`).  This patch removes the bracketing syntax, which is conventionally reserved for random access sequences.
Additionally, remove some cruft; consistently use `elements` for the constituents of a `Sequence`, and reserve `members` for declarations of a region.

Remove bracketing from Sequence

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/traversal.cxx

Various places in the ISO C++ semantics require _semantics by translation_ -- an unwise specification technique for an evolutionary and complex language.  This expression node captures the structure of that process.

Add `ipr::Rewrite`

---

include/ipr/impl

The `ipr::impl::traits` class template has been unnecessary for a while now.  Removed thusly.

Remove ipr::impl::traits

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

Add a second implementation class for `ipr::Where` that introduces local bindings.
Fixes #103 and #113.

Binding implementation for `ipr::Where`

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/io.cxx
src/traversal.cxx

Standard C++ does not assign types to constructor or destructor declarations.  The IPR, until now, has relied on platform ABI-dependent interpretations of those special functions as regular functions with some ABI-dependent return type.  A high level representation of C++ is expected to abstract over those differences.  This is the role of this new type `Tor` class.  It is essentially a `Function`, minus the `target()` type.

Add Tor type for object constructors and destructors

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
src/traversal.cxx

This patch adds support for ISO C++ _using-declaration_, modeled in the IPR as belonging to the category `ipr::Directive`.
A _using-declaration_ is an directive to a C++ compiler for perform lookup on certain _qualified-id_ s and introduce _synonymous_ declarations, subject to certain constraints.  The common case of a single _using-declarator_ in a _using-declaration_ has a dedicated, more efficient implementation than the generic case of _using-declarator-list_ of cardinality more than 1.

using-declaration as directive

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/traversal.cxx

Long forgotten IPR node.  Reported by @GorNishanov .

Add missing node for `alignof`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

The operation `Decl::position()` was to enable indexing into a scope based on position.  That model breaks down when a scope is made of pieces coming from various places (e.g. import of modules) in contemporary C++.  It does not seem to have lived up to its promises.  Removed thusly.

Remove `ipr::Decl::position`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

The result of name lookup may be empty.  Express that with `Optional`.
Remove `impl::empty_overload`.

Miscellaneous cleanup 8/n

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

This patch adds the `body()` operation to a `ipr::Region`: it returns the sequence of generalized expressions (classic expressions, statements, directives, declarations, etc.) that makes up a lexical region.
As a consequence, a function and user-defined types all have bodies: the sequence of expressions lexically written in their defining initializers.

Region has a body

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
src/impl.cxx
src/traversal.cxx

A _structured binding_ is a directive to to decompose an object (designated by an _initializer_) into a collection of declarations (`Alias` or `Var`), following a given binding mode.
Fixes #9 .

Structured_binding as directive

---

.github/workflows/analysis.yml
include/ipr/impl
include/ipr/interface
include/ipr/io
include/ipr/utility
infra/Analysis.ruleset
src/impl.cxx
src/io.cxx
src/utility.cxx

Add analysis ruleset to be used by the Microsoft C++ Code Analysis action. Warnings should be visible in the PR so this can be used to determine the scope of rules that will be useful for the IPR.

Enable rules for the Microsoft C++ Analysis action

---

include/ipr/ancillary
include/ipr/attribute
include/ipr/cxx-form
include/ipr/impl
include/ipr/interface
include/ipr/location
include/ipr/node-category
include/ipr/synopsis
src/impl.cxx
src/io.cxx
src/traversal.cxx
tests/unit-tests/conversions.cpp
tests/unit-tests/simple.cpp

This patch adds support for multiple _init-declarator_ s in a single declaration, as an IPR directive.
The patch also incorporates some Spring cleaning, which leads to source level breakage.
Fixes https://github.com/GabrielDosReis/ipr/issues/177

Multiple declarators in single declaration as a directive

---

include/ipr/interface

In general, the type of an initializer is that of its initializer -- especially for type aliases.  However, structured bindings can introduce aliases too (at object level) and the corresponding binding may have acquired a _cv-qualifier_.  Therefore, this patch removes the incorrect override in the interface of `Alias` -- since it is overriden later in the implementation, it is never executed.
In short, this is a removal of a wrong dead code.

The type of an alias is now always that of its initializer

---

include/ipr/utility
src/utility.cxx

Most of the `ipr/utility` header was written in the first half of the 2000s, and it shows :-)
This patch takes the opportunity of fixing an issue reported by the Analysis workflow to do some Spring cleaning, avoiding the good old unnamed `enum` trick in favor of typed `constexpr` variables.
Fixes #210

Cleanup `util::string::arena`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

While in general, a `Tor` type is close to a `Function` type and, in principle, should have a language linkage, that does not actually happen in practice.  This patch removes that possibility for now.  It should be reinstated when we have more evidence of its usefulness (non-`C++` language linkage constructors) in practice.

Simplify Tor type

---

include/ipr/impl
src/impl.cxx

Make them `constexpr`.
Back in the early 2004, there was no support for `constexpr` data (the constexpr feature was being debated by the C++ standards committee), so orderly initialization had to be hand rolled.  This patch takes advantages of `constexpr` to remove ceremonial computation and increase certainty around `C` and `C++` linkage data objects.
Fixes #213 #214

C and C++ linkage are known to all implementations

---

include/ipr/io
include/ipr/utility
src/io.cxx

The primary purpose of this patch is to remove a couple of places where `static_cast` is being used to beat a value into `int` representation.  That battle was lost a decade ago, and again with `std::span`.  Adjust to new reality.
As a secondary purpose, this patch introduces a utility to retrieve the underlying value representation of an enumeration value without using `static_cast`.
Fixes #216 
Fixes #217

Use utilities to deduce enumeration underlying type

---

STYLE.md
include/ipr/ancillary
include/ipr/impl
src/impl.cxx
tests/unit-tests/conversions.cpp
tests/unit-tests/simple.cpp

The patch that moved the `Name` hierarchy out of the `Expr` hierarchy left the factory functions as member of `expr_factory`.  This patch sequesters them in a dedicated factory type (`name_factory`), and:
- rename the `make_xxx` name factory functions to `get_xxx`
- change their return type to immutable reference to interface classes, instead of mutable pointer to implementation classes
These changes represent source-level breaking changes, but the fixes are mechanical.

`name_factory`: factories for names

---

include/ipr/impl
include/ipr/traversal
src/impl.cxx

This patch moves the representation of elementary, built-in types to be `constexpr` objects instead of being dynamically constructed at startup time.  In addition to improving reliability, it simplifies the structure of the implementation.

Built-in types as `constexpr` objects

---

src/impl.cxx

Fix new Code Analysis warning introduced in PR #220.

Make `impl::Typename::second()` final

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

This patch adds symbolic representation for `false` and `true` as built-in core values.

Symbolic truth values

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
src/io.cxx

Back in 2004, only types could be mentioned in function exception specification.  That ability was later known as _dynamic exception specification_.   The IPR representation at the time opted to integrate that directly in the type system even when it wasn't at the ISO C++ level.  Throwing anything was modeled by the ellipsis type `...`.
Very late in the C++11 development process, `noexcept` was introduced for specifying that a function call execution could throw something or not (without mentioning what the type of that thing could be).  While the operand (at the source level) can be an arbitrary expression, when fully evaluated, the value of the operand be only be `false` or `true`.
This patch adds ability to specify `noexcept`-ness in the type system.
Fixes #150

Upgrade representation of exception specification

---

include/ipr/impl
src/impl.cxx

Use `impl::Builtin` to define `impl::any_type` -- as it is a built-in type in every other aspect.

`impl::any_type` is built-in

---

include/ipr/impl
src/impl.cxx
tests/unit-tests/simple.cpp

This patch makes the symbolic representation of `nullptr` a constexpr object.  It also removes dead code.

`nullptr` symbol is constexpr

---

include/ipr/impl
src/impl.cxx

A `Type_id` name is unique by the virtue of being associated with a unique type.  We don't need a separate uniquing factory function for that.  Furthermore, uses of `Type_id` names is mostly internal, for technical reasons.  That factory function is gone with this patch.  That exposes further simplification opportunities of the existing implementation codebase - in preparation for making linkage part of all types.

Remove `name_factory::get_type_id`

---

include/ipr/impl
include/ipr/interface
include/ipr/synopsis
src/impl.cxx
src/io.cxx
src/traversal.cxx

Back in 2004,  `Rname` was introduced as a mathematical device to handle the situation where function declarations and template declarations are matched/unified without regard to the names of the parameters.  With the move to differentiating between core expressions (which are unified) and located expressions, it is no longer necessary to have `Rname` around.  Removed with this patch.  I took the opportunity to further simplify the implementation codebase.  This is a source-level breaking change.

Remove `Rname`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

This patch adds two things:
1. Labels as symbolic values of type `void`. Use `get_label(lbl)` to get the symbolic representation of `lbl` as a label.
2. `default` is a universal defaulter: It can be used as the initializer in a defaulted function definition, or as the default operand to `case` in a _labeled-statement_.  In both cases, use `Lexicon::default_value()`.

`default` is a symbolic value

---

include/ipr/impl
src/impl.cxx

The `this` implicit parameter is a `Symbol` that is valid within the context of non-static members.

`this` is  a symbolic value

---

include/ipr/impl
src/impl.cxx

This field is set in all implementations of `ipr::Region` but never used after a few refactoring.

Remove unused field `owned_by`

---

include/ipr/impl

The semantics and the implementation are more general than those of a declset, and applicable to a wider set of area.

Rename `impl::singleton_declset` to `impl::singleton_ref`

---

include/ipr/impl
include/ipr/interface

All declarations for which the notion of `unique_decl` applies have C++ language linkage.  Therefore, there is no point in actually storing that directly.  Furthermore, only `Base_type` needs the notion of `DeclSpecifiers`.  Finally, I tool the opportunity to rename `lang_linkage` to just `linkage`.

Simplify `impl::unique_decl`

---

include/ipr/impl
src/impl.cxx

The existing implementation is renamed to `impl::obj_list`.  An alternative implementation, based on `std::deque` is named `impl::obj_sequence`.  It is to be used for large collection of items.

Replace `impl::val_sequence` with two implementations

---

include/ipr/impl
src/impl.cxx

The general model of a scope is that it is a sequence of declarations.  The declarations are further divided into overload sets.  Each overload set contains a declset : all the declarations in that scope for the same name with the same type.
The existing implementation  `impl::unique_decl` contains `singleton_overload`, which is logically backward.  Fixed with this patch.  Now, a `homogeneous_scope` is a sequence of `singleton_overload` s.  Each `singleton_overload`, in turn, contains a decl(set).

Make `impl::singleton_overload` contain its declset

---

include/ipr/impl
src/impl.cxx

There are too many type factory functions.  Some in `impl::type_factory`, others in `impl::Lexicon`.  This patch consolidates all type factory functions at one place.  They are all of the from `get_xxx()`, as their results are immutable.  There is no expected change for callers of `impl::Lexicon` functions.

Clean up type factory functions

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

With the introduction of `ipr::Directive`, it  becomes necessary to widen the types of components of certain statements to fully represent all kinds of Standard C++ constructs at the statement level.

Generalize types of statement constituents

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
include/ipr/synopsis
src/impl.cxx
src/io.cxx
src/traversal.cxx

Use `impl::Lexicon::get_this()` to construct the symbolic representation for Standard C++'s  `this`.

Remove `ipr::This`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
src/traversal.cxx
tests/unit-tests/simple.cpp

In preparation for simplifying how declarations are created and entered in declarative regions.

Clean up `impl::Udt`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
src/traversal.cxx

At some point in mid 2000s, I introduced  `Empty_stmt` as a way to "optimize" the representation of empty statement.  However, it turns out to introduce irregularity and confusion.  Removed by this patch.  Similarly, `Primitive` is removed.

Remove `ipr::Empty_stmt`

---

3rdparty/doctest/doctest.h

Update to the latest version of doctest 2.4.8
This is required to get gcc builds to work on Linux due to SIGSTKSZ becoming a variable.
I'm not sure about contribution guidelines. Do you want an issue created for each PR?

Update doctest to 2.4.8 from 2.4.0

---

include/ipr/utility

The implementation now matches the stated goal of the function.
Without this fix, we get segmentation fault/access violation once we ran out of space in the buffer, as original `remaing_header_count` will keep returning bigger and bigger number as the `next_header` is advanced forward in the buffer.

Fix arena::remaining_header_count

---

include/ipr/interface

The implementation always have Product as its type.
Making the type more precise in the interface can simplify
user code making some casts redundant.

Make Parameter_list type more precise

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
include/ipr/synopsis
src/impl.cxx
src/traversal.cxx

To capture the description of an instantiation of a templated expression, along with the substitution used and the result of the instantiation.

Add `ipr::Instantiation`

---

include/ipr/impl
include/ipr/interface

Provide accessor for the underlying type of an enumeration.
Partially addresses #22 .

Base type of an enum

---

include/ipr/impl

Remove `impl::Template::args`

---

CMakeLists.txt

Visual Studio requires explicit listing of files when you generate a solution
This adds the headers and the .md files to the ipr project
The block in the CMakeLists.txt file could be enclosed in a 
`if (CMAKE_GENERATOR MATCHES "Visual Studio")`
if there is a worry that could effect other build systems but it should not

Add files to CMakeLists.txt so they show up in Visual Studio

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
include/ipr/synopsis
src/impl.cxx
src/io.cxx
src/traversal.cxx
tests/unit-tests/conversions.cpp

One of the early semantic design decisions of the IPR was to view base-class types as declaring anonymous fields of the derived classes, as documented in the C++ ARM (original C++ semantics documentation).  Over the years, that approach has felt at odd with other semantic aspect of the declarative model of the IPR.  This patch removes `Base_type` as a `Decl`, and instead replaces it with just a specifier for base class layout indicator for semantic interpretations in later interpretations (e,g. object layout, object initialization, etc).
Fixes #65

Remove `Base_type`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx
tests/unit-tests/CMakeLists.txt
tests/unit-tests/region-owner.cxx

* Restored owner to region.
* Added a test with a use case
There are three implementation nodes that host a Parameter_list.
Mapping and Lambda will setup the Paramater_list region owner to themselves.
Callable_species will leave the owner null. This requires more thinking.
Issue: https://github.com/GabrielDosReis/ipr/issues/268

restore ipr::Region::owner(), added a usage example

---

include/ipr/impl
include/ipr/interface
include/ipr/node-category
include/ipr/synopsis
src/impl.cxx
src/traversal.cxx
tests/unit-tests/CMakeLists.txt
tests/unit-tests/phased-eval.cxx

Both _asm-declaration_ and _static\_assert-declaration_ are now uniformly represented as phased evaluation of the generalized expressions `ipr::Asm` and `ipr::Static_assert`.
This unified description comes at the cost of an indirection going from a `Directive` to an `Expr`.  However, it allows for other type expressions (e.g. parameterized _prolongation_ s) to be described in the same scheme.  Furthermore, an `if constexpr` and an `if consteval` are now just phased evaluation of ordinary _if-statement_.  Similarly, static initialization can also be described as a phased evaluation.

Add `ipr::Phased_evaluation`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

This patch is the first in a series to refactor the interface and implementation of `Mapping`.
This PR removes `ipr::Mapping::target()` and its implementation.
A mapping should just be an expression that maps a set of inputs to an output.  The type of the output should be set and retrieved from the entity for which a `Mapping` is used as initializer, thereby reducing redundancy.
This patch is potentially a source breaching change for users that set and retrieve `target()`.

Refactor `Mapping` [1/n]

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

Capture structural commonality of parameterized entities once in the form of `Parameterization`.  Remove boilerplate.

Refactor `Mapping` [2/n]

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

In general, IPR node implementation classes are immotile.  On a very few occasions, there is a need for certain nodes to be moveable (e.g. `impl::Parameter_list`).  This patch splits the previous implementation class template `impl::Node` in two categories: (a) `impl::immotile_node`; and (b) `impl::Node`.
The new `impl::Node` has move semantics while `impl::immotile_node` does not.
This patch also has a new breaking change: previously a `Return` node has its type equal to its `operand()`.  However, that was incorrect.  A return statement can trigger implicit conversion to bring its `operand()` to the return type, so the two types are not - in general - the same.  From now on, `impl::Return` nodes need to explicitly set their types.

Distinguish immotile nodes from the exceptions

---

src/traversal.cxx

As an `ipr::Node`.
Spotted by @jimspr

Default visit of `Annotation`

---

include/ipr/interface

More recent versions of the language allow declaring destructors without negatively affecting `constexpr` capabilities.

Make `Node` constructor protected

---

include/ipr/synopsis

It is just a set of forward declarations of classes with brief commentary.

`<ipr/synopsis>` should have no dependency

---

include/ipr/ancillary
include/ipr/attribute
include/ipr/impl
include/ipr/interface

@JimSpr observed that `ipr::Attribute` hierarchy wasn't using the structural templates `Unary` and `Binary`.  Fixed with this patch

Use `Unary` and `Binary` for `Attribute`

---

include/ipr/cxx-form
include/ipr/impl
src/impl.cxx

Split the class `cxx_form::Indirector::Simple` into two:
- `cxx_form::Indirector::Pointer`, and
- `cxx_form::Indirector::Reference`.
Adjust the return type of `cxx_form::Indirector::Member::whole()` to `Expr`.
This is a source breaking change.

Rework indirector form hierarchy

---

include/ipr/cxx-form
include/ipr/impl
src/impl.cxx
tests/unit-tests/region-owner.cxx

This patch rewrites the data structures for declarator species, both correcting and simplifying the representations.  Now, a declarator species is either an `Species_declarator::Id` or a `Species_declarator::Parenthesized` followed by a suffix of `Morphism`s.  A `Morphism` indicates either an array or a function type constructor.

Rework of declarator species

---

include/ipr/cxx-form
include/ipr/impl
src/impl.cxx

This patch replaces the class `cxx_form::Declarator::Id` with three classes that better represent the various alternatives of the C++ grammar production for _declarator-id_.  This allows the resulting structures to be used in more natural representations of the grammar production _abstract-declarator_.

Refine C++ form for _declarator-id_

---

include/ipr/cxx-form
include/ipr/impl
src/impl.cxx

This patch expands on the various forms of initializers in a proclamator form for C++ source code.
As a small extension, these initializer forms are capable of also representing C99's designated initializers for arrays, which is not ISO C++ but common in practice.

Expand on C++ forms for initialization

---

include/ipr/cxx-form
include/ipr/impl
include/ipr/interface
include/ipr/node-category
include/ipr/synopsis
src/impl.cxx
src/traversal.cxx

This patch adds representations (C++ forms) for C++20 constraints which are syntactic requirements on combinations of template arguments lists.
Fixes #181

Add support for constraints

---

CMakeLists.txt
include/ipr/impl
include/ipr/interface
include/ipr/io
include/ipr/utility
src/impl.cxx
src/io.cxx
tests/unit-tests/CMakeLists.txt
tests/unit-tests/phased-eval.cxx
tests/unit-tests/simple.cxx
tests/unit-tests/specifiers.cxx

This patch rewrites the representation of ISO C++ _decl-specifier-seq_ grammar instances in form of symbolic and algebraic denotations.  This allows non-standard extensions while retaining efficient manipulations of them as bitmasks.

Denotation for decl-specifier

---

include/ipr/ancillary
include/ipr/cxx-form
include/ipr/impl
include/ipr/interface
include/ipr/io
include/ipr/utility
src/impl.cxx
src/io.cxx
tests/unit-tests/conversions.cxx
tests/unit-tests/simple.cxx

Just like the case of _decl-specifier-seq_ , this patch rewrites the representation of type qualifiers in both symbolic and algebraic form, offering both extensions (for vendor-specific type qualifiers) and efficiency (operations remain bitmask operations).
This patch introduces source-level breaking changes.

Symbolic denotation of type qualifiers

---

CMakeLists.txt
include/ipr/input
src/input.cxx
tests/unit-tests/specifiers.cxx

The data type `ipr::input::SourceFile` abstracts away the ceremonies of memory mapping an input source file into memory as a sequence of raw bytes.

Add `ipr::input::SourceFile`

---

include/ipr/input
src/input.cxx

Mark `ipr::input::SourceFile` move constructor as noexcept.

Resolve SA alert 4447

---

CMakeLists.txt
include/ipr/impl
include/ipr/interface
include/ipr/node-category
include/ipr/synopsis
include/ipr/utility
src/traversal.cxx

And support for _explicit object parameter_ description in the IR.

Add `ipr::FunctionTraits`

---

include/ipr/impl
include/ipr/interface
src/impl.cxx

With modules in C++20, "name linkage" is picking up more steam in conversations and we need to make the terms a bit more explicit.

Rename `ipr::Linkgage` to `ipr::Language_linkage`

---

src/input.cxx

The line reader missed the situation that line splicing into an entirely blank logical line ends the in-progress line splicing.

Splicing into entirely blank logical line
