- include/ipr/impl
- include/ipr/interface
- src/impl.cxx
> Fix storage for function parameters

- include/ipr/impl
- include/ipr/interface
> A declaration may not have a matching definition.

- .github/workflows/main.yml
This is a small job that checks the project out and builds it using CMake on Ubuntu.
> Create a basic CI to compile project

- .github/workflows/mac.yml
- .github/workflows/main.yml
Alter the build command to utilize multiple cores in CI VMs.
> Parallel build in CI

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- src/impl.cxx
- src/traversal.cxx
> Support fold expressions

- include/ipr/interface
- include/ipr/node-category
- src/traversal.cxx
Bug fixes for PR #112
- Category code was not set correctly
- Visitor hierarchy skipped classic
> Fix bugs with recent conversion PR

- include/ipr/interface
This PR updates some comments that have shown their age.  It also expands on a couple of aims that were described in the IPR paper.
> Miscellaneous comment cleanup

- include/ipr/interface
> Add comment for Construction

- include/ipr/impl
> Remove impl::homogeneous_sequence

- include/ipr/impl
- include/ipr/interface
- src/impl.cxx
> Complete ipr::Attribute hierarchy

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- src/impl.cxx
- src/io.cxx
- src/traversal.cxx
> ipr::Noexcept

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- src/impl.cxx
- src/io.cxx
- src/traversal.cxx
> ipr::Args_cardinality

- src/impl.cxx
Remove some good amount of copy-n-paste.
> Consolidate boilerplate into abstraction

- include/ipr/impl
- src/impl.cxx
> Less unification for unary expression structures

- src/impl.cxx
> Set type of `auto` type expression

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- src/impl.cxx
- src/traversal.cxx
- tests/unit-tests/conversions.cpp
Added the remaining standard conversions and demonstrative tests.
> Added additional conversions.

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- include/ipr/traversal
- src/impl.cxx
- src/io.cxx
- src/traversal.cxx
> Representation of lambda expressions

- CMakeLists.txt
Ask CMake to require C++20 (through whichever form it is available) to build the main library.
> Select C++20 for build

- STYLE.md
- include/ipr/impl
- include/ipr/interface
- include/ipr/utility
- src/impl.cxx
- src/io.cxx
- src/traversal.cxx
- src/utility.cxx
Use `not`, `and`, and `or` for logical connectives.
> Miscellaneous cleanup 7/n

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- src/impl.cxx
- src/traversal.cxx
The implementation is pretty much what the feature request and discussion say.
Fixes #113
> Implement Where expression node

- .github/workflows/main.yml
By invoking action to set up the Visual Studio Developer Command
> Fix build and test environment on Windows

- include/ipr/impl
As reported by the Code Analysis workflow.
> Static Analysis result cleanup 1/n

- include/ipr/impl
- include/ipr/interface
- include/ipr/node-category
- include/ipr/synopsis
- src/impl.cxx
- src/io.cxx
- src/traversal.cxx
- tests/unit-tests/conversions.cxx
Reverts GabrielDosReis/ipr#265
> Revert "Remove `Base_type`"

- include/ipr/impl
- include/ipr/interface
- tests/unit-tests/warehouse.cxx
Add more description, and fix a couple of type thinkos.
> Cleanup up `owner()` after resurrection

- CMakeLists.txt
> Enable link-time optimization

- .github/workflows/docs.yaml
- .github/workflows/main.yml
Details are at https://github.com/actions/runner-images/issues/7192
> Workaround GH ubuntu-latest runner issue

- .github/workflows/main.yml
> Update compiler versions on ubuntu-latest

- README.md
Reverts GabrielDosReis/ipr#300
> Revert "Add Windows-based CI status badge"
